# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: IT-Women-Esbjerg/it-women-esbjerg-website

media_folder: /public/media
public_folder: /media

collections:
- name: events
  label: Events
  label_singular: Event
  folder: /content/events
  fields:
  - { name: title, label: Title, widget: string }
  - { name: draft, label: Draft, widget: boolean }
  - { name: description, label: Description, widget: richtext }
  - { name: event_start, label: Event Start, widget: datetime }
  - { name: event_end, label: Event End, widget: datetime }
  - { name: location, label: Location, widget: string }
  - { name: poster, label: Poster, widget: image }
  - { name: plans, label: Plans/Agenda, widget: list, fields: [ { name: plan, label: Plan, widget: string } ] }
  - { name: takeaways, label: Takeaways, widget: list, fields: [ { name: takeaway, label: Takeaway, widget: string } ] }
  - { name: images, label: Images, widget: list, fields: [ { name: image, label: Image, widget: image } ] }

media_libraries:
  cloudinary:
    config:
      cloud_name: dnwahijsm
      api_key: 737422483695581
